---
# todo:
# 1. put paths into variables so they can easily be modified
# 2. clean up resources on big-ip
- name: "Get bigip status of virtuals, pools, nodes, and routes"
  hosts: ssh
  gather_facts: false
  connection: local
  vars:
    filename: "{{ lookup('pipe', 'date +%FT%H%MZ') }}-data_collection.log"

  tasks:
    - name: "Write out data collection script"
      blockinfile:
        create: yes
        path: /var/tmp/data_collection_script.sh
        content:  |

          tmsh show ltm virtual | grep "Virtual Server:\|Availability\|State" | xargs -n3 -d'\n' | sort
          tmsh show ltm pool | grep "Pool:\|Availability\|State" | xargs -n3 -d'\n' | sort
          tmsh show ltm node | grep "Node:\|Availability\|State" | xargs -n3 -d'\n' | sort

          imish << EOF
          en
          show ip route | exclude (-|Gateway of last resort)
          show bgp ipv4 neighbors
          EOF

    - name: "Add shell tag"
      lineinfile:
        path: /var/tmp/data_collection_script.sh
        insertbefore: '^# BEGIN ANSIBLE MANAGED BLOCK'
        line: '#!/bin/bash'

    - name: "Run Script"
      shell: bash /var/tmp/data_collection_script.sh > /var/tmp/{{filename}}

    - name: "Collect Script"
      fetch:
        flat: true
        dest: /var/tmp/{{filename}}
        src: /var/tmp/{{filename}}

