---
- name: "Get bigip status of virtuals, pools, nodes, and routes"
  hosts: ssh
  gather_facts: false
  connection: local
  vars:
    filename: "{{inventory_hostname}}-BEFORE-{{ lookup('pipe', 'date +%FT%H%MZ') }}.log"
    script_file: "{{device_working_dir}}/data_collection_script.sh"
    data_file: "{{device_working_dir}}/{{filename}}"

  tasks:
    - name: "Write out data collection script"
      blockinfile:
        create: yes
        path: '{{script_file}}'
        content:  |

          tmsh show ltm virtual | grep "Virtual Server:\|Availability\|State" | xargs -n3 -d'\n' | sort
          tmsh show ltm pool | grep "Pool:\|Availability\|State" | xargs -n3 -d'\n' | sort
          tmsh show ltm node | grep "Node:\|Availability\|State" | xargs -n3 -d'\n' | sort

          imish << EOF
          en
          show ip route | exclude (-|Gateway of last resort)
          show bgp ipv4 neighbors
          EOF

    - name: "Add shell tag"
      lineinfile:
        path: '{{script_file}}'
        insertbefore: '^# BEGIN ANSIBLE MANAGED BLOCK'
        line: '#!/bin/bash'

    - name: "Run Script"
      shell: 'bash {{script_file}} > {{data_file}}'

    - name: "Collect Script"
      fetch:
        flat: true
        dest: '{{mount_dir}}/reports/{{filename}}'
        src: '{{data_file}}'

