---
- name: BIG-IP reboot into new volume
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false

    - name: Reboot into new volume
      bigip_command:
        provider: "{{provider}}"
        commands: reboot volume {{new_volume}}

    - name : Wait for system to restart and become unreachable
      wait_for:
        host: "{{private_ip}}"
        port: 443
        state: stopped

    - name: Wait for restart to complete
      uri:
        url: "https://{{ ansible_host }}:443/mgmt/shared"
        method: GET
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: f5networks
      until: f5networks is not failed
      retries: 45

