---
- name: "Compare the two snapshots"
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - name: "Compare the two snapshots"
    local_action: shell diff /tmp/*.log
    register: diff_output

  - name: "Output diff"
    debug:
      var: diff_output