---
- name: BIG-IP create UCS and save locally off-box
  hosts: LB
  connection: local
  gather_facts: false
  vars:
    # filename: "{{inventory_hostname}}-{{ lookup('pipe', 'date +%FT%H%MZ') }}-backup.ucs"
    # trusted_checksum: "{{lookup('file', '{{repo_path}}/{{f5_image}}.md5').split(' ').0}}"
    # backup_dir: "/f5data/backups"
    upgrade_image: "BIGIP-17.1.1.1-0.0.2.iso"
    repo_path: "/mnt/apps/isos/VMware/Appliances/F5/17.x/"
  roles:
    # - roles/F5/create_ucs
    # - roles/F5/refresh_license
    - roles/F5/upload_upgrade_f5
    # - roles/F5/upgrade_reboot

# - name: "Get bigip status of virtuals, pools, nodes, and routes"
#   hosts: ssh
#   gather_facts: false
#   connection: local
#   vars:
#     # filename is built to hold the report name.  Its timestamped and designated with BEFORE which is used in comparison
#     # script_file is the script that is echoed on the device and ran to collect information
#     # data_file is the out of the script file or the report.  Note this goes to a mounted directory in the EE!  Important.
#     # device_working_dir, and report_dir are defined in the hosts/inventory
#     filename: "{{inventory_hostname}}-{{ lookup('pipe', 'date +%FT%H%MZ') }}-AFTER.log"
#     script_file: "{{device_working_dir}}/data_collection_script.sh"
#     data_file: "{{device_working_dir}}/{{filename}}"
#   roles:
#     - roles/General/collection_scripts

# - name: BIG-IP create UCS and save locally off-box
#   hosts: lb
#   connection: local
#   gather_facts: false

#   roles:
#     - roles/General/compare_data