---
- name: "Get bigip status of virtuals, pools, nodes, and routes"
  hosts: LB
  gather_facts: false
  vars:
    # filename is built to hold the report name.  Its timestamped and designated with BEFORE which is used in comparison
    # script_file is the script that is echoed on the device and ran to collect information
    # data_file is the out of the script file or the report.  Note this goes to a mounted directory in the EE!  Important.
    # device_working_dir, and report_dir are defined in the hosts/inventory
    filename: "{{inventory_hostname}}-{{ lookup('pipe', 'date +%FT%H%MZ') }}-AFTER.log"
    script_file: "{{playbook_dir}}/data_collection_script.sh"
    data_file: "{{playbook_dir}}/{{filename}}"
    report_dir: "/f5data/reports"
  roles:
    - roles/General/collection_script

- name: BIG-IP create UCS and save locally off-box
  hosts: LB
  gather_facts: false
  vars:
    report_dir: "/f5data/reports"
  roles:
    - roles/General/compare_data